apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: cGFkbWFzcmlrYW50aA== # base64-encoded value of 'username'
  password: cGFkbWFzcmlrYW50aDEyMw== # base64-encoded value of 'password'