apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: resource
    image: techworldwithsiva/stress 
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"       
  - name: almalinux
    image: almalinux
    command: ["sleep" , "2000"]