apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http-pod
spec:
  containers:
  - name: liveness
    image: nginx
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3