apiVersion: v1
kind: Pod
metadata:
  name: env-pod-comp
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
        - configMapRef:
            name: myconfigmap