apiVersion: v1
kind: Pod
metadata:
  name: clusterippod
  labels:
    service: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80        

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-clusterip
spec:
  selector:
    service: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: almalinux
    image: almalinux
    command: ["sleep" ,"20000"]

