apiVersion: v1
kind: Pod
metadata:
  name: loadbalancerpod
  labels:
    service: nginx_loadbalancer
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80        

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    service: nginx_loadbalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80