apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  DEMO_GREETING: "Hello from the environment"
  DEMO_FAREWELL: "Such a sweet sorrow"
  DEMO_MSG: "Work hard"
  DURITAION: 30hrs
  NAME: padmasrikanth